# File: environment.yml
# Created Date: Saturday February 13th 2021
# Author: Steven Atkinson (steven@atkinson.mn)

name: nam
channels:
  - conda-forge # pytest-mock
  - pytorch
  - nvidia
dependencies:
  - black
  - flake8
  - h5py
  - jupyter
  - matplotlib
  - numpy
  - pip
  - pydantic
  - pytest
  - pytest-mock
  - pytorch
  - pytorch-cuda=11.7
  - scipy
  - semver
  - tensorboard
  - tqdm
  - wheel
  - pip:
      - auraloss==0.3.0
      - onnx
      - onnxruntime # TODO GPU...
      - pre-commit
      - pytorch_lightning
      - sounddevice
      - wavio
      - -e .
